name: flutter_3d
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.0.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uploadcare_client: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
